name: scripture
description: the Holy Bible in languages

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'
version: 1.2.6+83

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  lidea:
    # When depending on this package from a real application you should use:
    #   lidea: ^x.y.z
    # path: ../../
    path: ../lidea
    # git:
    #   url: git://github.com/laisiangtho/lidea.git
    #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # Add assets
  assets:
    - assets/env.json
    - assets/bible.json
    - assets/book.json
    # - assets/niv2011.json
    # - assets/tedim1932.json
    # - assets/judson1835.json

  # fonts from lidea
  fonts:
    - family: Lato
      fonts:
        - asset: packages/lidea/fonts/Lato-Regular.ttf
        - asset: packages/lidea/fonts/Lato-Thin.ttf
        - asset: packages/lidea/fonts/Lato-Light.ttf
        - asset: packages/lidea/fonts/Lato-Bold.ttf

    - family: Lidea
      fonts:
        - asset: packages/lidea/fonts/Lidea.ttf

    - family: Mm3Web
      fonts:
        - asset: packages/lidea/fonts/Mm3Web.ttf
